### PR TITLE
[WIP] swap out Husl for Hsluv

### LINKED ISSUE #43: HuSL deprecated, use HSLuv instead
Hi there,
Some time ago [HuSL](https://www.npmjs.com/package/husl) was deprecated and replaced by [HSLuv](https://www.npmjs.com/package/hsluv). Although they are functionally the same, only hsluv is actively maintained.

Could we consider swapping these packages?

### PR DESCRIPTION
**Pull request by chrisgervang**
Fixes #43.
Need to wait for hsluv/hsluv#46 to be closed before tests work.

### CODE REVIEW

**Comment by boronine** [comment]
Your changes were release in [0.0.3](https://www.npmjs.com/package/hsluv), you should be good to go!

**Comment by dfcreative** [comment]
Thanks so much @chrisgervang for the effort! Released as 1.16.0

**Comment by chrisgervang** [comment]
@dfcreative Thanks! No problem! But, I think this wasn't actually ready to merge yet until the package gets updated and the tests pass 😬 I'll send a follow up PR tomorrow (I'm heading to bed now)

**Comment by chrisgervang** [comment]
Oh, nm. I see you actually fixed it in a follow up commit. Thanks!

**Pull request merged**
